NumPy

In [1]:
import numpy as np

Membandingkan kecepatan antara NumPy dengan List Core Python

In [3]:
#List Core Python
def python_listsum(n):
    a = b = list(range(n))
    output = []
    for idx in range(len(a)):
        x = a[idx] ** 2
        y = b[idx] ** 3
        output.append(x + y)
        
    return output

output_listsum = python_listsum(10)
print(output_listsum)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [5]:
#NumPy
def numpy_sum(n):
    x = np.arange(n) ** 2
    y = np.arange(n) ** 3
    return x + y

output = numpy_sum(10)
print(output)

[  0   2  12  36  80 150 252 392 576 810]


In [8]:
from datetime import datetime
size = 1000000
awal = datetime.now()

output = numpy_sum(100)
end = datetime.now() - awal

print(f"Waktu yang dibutuhkan : {end.microseconds}")
print(f"Data 2 akhir dari list : {output[-2:]}")

Waktu yang dibutuhkan : 1001
Data 2 akhir dari list : [950796 980100]


# Ndarrays

In [9]:
listrange = list(range(5))
print(listrange)
print(type(listrange))

[0, 1, 2, 3, 4]
<class 'list'>


In [10]:
nparr = np.array(listrange)
print(nparr)
print(type(nparr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
#start default = 0, stop, step default = 1
print(np.arange(5))
print(np.arange(1,9))
print(np.arange(1,15,2))

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[ 1  3  5  7  9 11 13]


## Add, Remove, and Sort

In [13]:
nparr = np.arange(1, 11)
print(nparr)
print(type(nparr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


Add

In [14]:
new_np = np.append(nparr, [12,14])
print(new_np)

[ 1  2  3  4  5  6  7  8  9 10 12 14]


Remove

In [15]:
new_np = np.append(nparr, [12,14])
print(new_np)

[ 1  2  3  4  5  6  7  8  9 10 12 14]


In [16]:
np.delete(new_np, 4)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 12, 14])

Sort

In [17]:
arr_acak = np.array([4,2,1,10,6,8,5,7,3])
arr_sort = np.sort(arr_acak)
print(arr_sort)

[ 1  2  3  4  5  6  7  8 10]


# Multi-Dimensional Arrays

## Ndim, Shape, and Size

2 Dimensi

In [19]:
multiplelist= [[0,1,2,3], [10,11,12,13]]
print(multiplelist)

np_arr = np.array(multiplelist)
print(f"{np_arr}")
print(f" nidm : {np_arr.ndim}, shape : {np_arr.shape}, size : {np_arr.size}")

[[0, 1, 2, 3], [10, 11, 12, 13]]
[[ 0  1  2  3]
 [10 11 12 13]]
 nidm : 2, shape : (2, 4), size : 8


ndim -> jumlah sumbu atau dimensi dari array

size -> jumlah total elemen array

shape -> tupel bilangan bulat yang menunjukkan jumlah elemen yang disimpan disetiap dimensi array

3 Dimensi

In [20]:
np_arr3 = np.array (  [
             [[0,1,2,3],[4,5,6,7]],
             [[8,9,10,11],[12,13,14,15]],
             [[20,21,22,23],[24,25,26,27]]
              ])

print(np_arr3)
print(np_arr3.shape)
print(np_arr3.size)
print(np_arr3.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[20 21 22 23]
  [24 25 26 27]]]
(3, 2, 4)
24
3


## Reshape

reshape -> memberikan bentuk baru ke array tanpa mengubah datanya

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


## Sorting

In [23]:
field_mhs  = [('name','S10'), ('ipk',float), ('age',int)]
value_mhs = [('Sule',3.5, 25), ('Azis',3.9, 24), ('Parto',3.2, 30), ('Andre',3.2, 24) ]

print("Field mahasiswa : ", field_mhs)  
print("Value mahasiswa : ", value_mhs)

Field mahasiswa :  [('name', 'S10'), ('ipk', <class 'float'>), ('age', <class 'int'>)]
Value mahasiswa :  [('Sule', 3.5, 25), ('Azis', 3.9, 24), ('Parto', 3.2, 30), ('Andre', 3.2, 24)]


In [25]:
data_mhs = np.array(value_mhs, dtype = field_mhs)
print(data_mhs)

[(b'Sule', 3.5, 25) (b'Azis', 3.9, 24) (b'Parto', 3.2, 30)
 (b'Andre', 3.2, 24)]


In [26]:
data_sortby_name = np.sort(data_mhs, order='name')
data_sortby_ageipk = np.sort(data_mhs, order=['age','ipk'])

print("Data sort by name : ", data_sortby_name)
print("Data sort by age and ipk : ", data_sortby_ageipk)

Data sort by name :  [(b'Andre', 3.2, 24) (b'Azis', 3.9, 24) (b'Parto', 3.2, 30)
 (b'Sule', 3.5, 25)]
Data sort by age and ipk :  [(b'Andre', 3.2, 24) (b'Azis', 3.9, 24) (b'Sule', 3.5, 25)
 (b'Parto', 3.2, 30)]


### Zeroes (sorting with structure)

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

# Convert 1D to 2D

In [30]:
datad = np.arange(2,8) 
print(datad)
print(datad.shape)
print(datad.ndim)

[2 3 4 5 6 7]
(6,)
1


In [31]:
new_datad = datad[np.newaxis]
print(new_datad)
print(new_datad.shape)
print(new_datad.ndim)

[[2 3 4 5 6 7]]
(1, 6)
2


In [32]:
vector_column = datad[ : ,np.newaxis]
print(vector_column)
print(vector_column.shape)
print(vector_column.ndim)

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(6, 1)
2


# Indexing and Slicing

In [33]:
datanp = np.array([0,1,2,3,4,5,6,7,8,9])
print(datanp)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(datanp[1])
print(datanp[-1])

1
9


In [35]:
print(datanp[1:5])

[1 2 3 4]


In [36]:
print(datanp[-2:])

[8 9]


## Slicing Menggunakan Kondisi Tertentu

In [37]:
list2d = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
np2d = np.array(list2d)
print(np2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
print(np2d[np2d<6])

[0 1 2 3 4 5]


In [41]:
kondisi_lebihdari_7 = (np2d >7)
print(np2d[kondisi_lebihdari_7])                    

[ 8  9 10 11]


In [42]:
kondisi2 = (np2d > 3) & (np2d <7)
print(np2d[kondisi2])

[4 5 6]


In [43]:
print(np2d[np2d % 2 == 1])

[ 1  3  5  7  9 11]


# Creating Array from Existing Data

## Slicing Indexing

In [44]:
np_arr1 = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np_arr1[4:9])

[5 6 7 8 9]


In [45]:
np_a2d = np.array([[1,1],[2,2]])
np_b2d = np.array([[3,3],[4,4]])
print(np_a2d)
print(np_b2d)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


## np.vstack()

In [46]:
npv = np.vstack((np_a2d, np_b2d))
print(npv)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


## np.hstack()

In [47]:
nph = np.hstack((np_a2d, np_b2d))
print(nph)

[[1 1 3 3]
 [2 2 4 4]]


## np.hsplit()

In [48]:
arr_s = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(arr_s)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [49]:
res_split = np.hsplit(arr_s,5)
print(res_split)
print(type(res_split))

[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4],
       [13, 14]]), array([[ 5,  6],
       [15, 16]]), array([[ 7,  8],
       [17, 18]]), array([[ 9, 10],
       [19, 20]])]
<class 'list'>


## view()

In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## copy()

In [54]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [55]:
np1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np1d.sum())

36


In [56]:
np2da = np.array([[10, 20],[30, 50]])

print(np2da)
print("#"*10)
print(np2da.sum(axis=0)) # menjumlahkan baris 
print("#"*10)
print(np2da.sum(axis=1)) # menjumlahkan kolom 

[[10 20]
 [30 50]]
##########
[40 70]
##########
[30 80]


In [57]:
data = np.array([1, 2])
data

array([1, 2])

In [58]:
ones = np.ones(2)
ones

array([1., 1.])

In [59]:
data + ones

array([2., 3.])

In [60]:
data - ones

array([0., 1.])

In [62]:
data * ones

array([1., 2.])

In [65]:
data * data

array([1, 4])

In [63]:
data / ones

array([1., 2.])

In [66]:
data / data

array([1., 1.])

# Broadcasting

In [67]:
data * 2

array([2, 4])

# More Array Operations

In [70]:
np1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np1d)

[1 2 3 4 5 6 7 8]


In [71]:
print(np1d.max())
print(np1d.min())
print(np1d.sum())

8
1
36


# Matrices

## Creating Matrices

In [72]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [73]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [74]:
np.random.random((3, 2))

array([[0.44277551, 0.34391117],
       [0.20248061, 0.4495524 ],
       [0.4171727 , 0.70235883]])

## Matrices Arithmetic

In [75]:
m_data =np.array([[1,2],[4,5]])
print(m_data)

[[1 2]
 [4 5]]


In [77]:
np_one = np.ones([2,2])
print(np_one)

[[1. 1.]
 [1. 1.]]
[[2. 3.]
 [5. 6.]]


In [78]:
print(m_data + np_one)

[[2. 3.]
 [5. 6.]]


## Dot Product

In [79]:
np.dot(3, 4)

12

## Matrix Indexing

In [80]:
data_m = np.array([[1, 2], [3, 4], [5, 6]])

print(data_m)
print("*"*10)
print(data_m[0,1]) ## baris ke 0 dan kolom ke 1
print(data_m[1:]) ## baris ke 1 sampai ke 3 (3 tidak include) dan untuk semua kolom
print(data_m[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
**********
2
[[3 4]
 [5 6]]
[1 3]


In [81]:
vkotak = np.arange(1,17,1)
print(vkotak)

kotak4x4 = vkotak.reshape(4,4)
print(kotak4x4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [82]:
print(kotak4x4[1::2, 0::2])
print(kotak4x4[1,2:4])
print(kotak4x4[:,1])
print(kotak4x4[-2:, 2:])

[[ 5  7]
 [13 15]]
[7 8]
[ 2  6 10 14]
[[11 12]
 [15 16]]


## Matrix Aggregation

In [84]:
np2da = np.array([[1, 2],[4,6],[8,10]])

print(np2da)
print(np2da.max())
print(np2da.min())
print(np2da.sum())

[[ 1  2]
 [ 4  6]
 [ 8 10]]
10
1
31


## Transposing and Reshaping

In [86]:
datat = np.array([[1,2],[3,4],[5,6]])

print(datat)
print("Data transpose : ", datat.transpose())
print("Data transpose : ", datat.T)

[[1 2]
 [3 4]
 [5 6]]
Data transpose :  [[1 3 5]
 [2 4 6]]
Data transpose :  [[1 3 5]
 [2 4 6]]


In [87]:
dataT = np.array([[1,2,3,4,5,6]]).T
print(dataT)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [88]:
print(dataT.reshape(2,3))
print(dataT.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# Flatten N-Dimensional Array

In [89]:
datat = np.array([[1,2],[3,4],[5,6]])
data_flat = datat.flatten()
print(data_flat)

[1 2 3 4 5 6]


# Working with Math Formulas

In [90]:
np_ds = np.arange(12)
print(np_ds)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [91]:
print(np_ds.dtype)
print(np_ds.shape)
print(np_ds.strides)

int32
(12,)
(4,)


In [92]:
np_ds_2d = np_ds.reshape(4,3)
print(np_ds_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [93]:
print(np_ds_2d.dtype)
print(np_ds_2d.shape)
print(np_ds_2d.strides)

int32
(4, 3)
(12, 4)


In [94]:
np_ds_int16 = np_ds_2d.astype('int16')

np_ds_int16.strides 

(6, 2)