Descriptive Statistics

In [93]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [94]:
math.nan

nan

In [95]:
np.nan

nan

In [96]:
x = [8,1,2.5,4,28]
x_with_nan = [8,1,2.5,np.nan,4,28]
print(x)
print(x_with_nan)

[8, 1, 2.5, 4, 28]
[8, 1, 2.5, nan, 4, 28]


In [97]:
#buat array(y) dan Series(z) dari x
y , y_with_nan = np.array(x), np.array(x_with_nan) #array
z , z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [98]:
z_with_nan.isna()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

# Measure of Central Tendency

## Mean

### Arithmetic Mean

In [99]:
x

[8, 1, 2.5, 4, 28]

In [100]:
sum(x)

43.5

In [101]:
len(x)

5

In [102]:
mean_x = sum(x)/len(x)
mean_x

8.7

In [103]:
mean_stats = statistics.mean(x)
print(mean_stats)

8.7


In [104]:
mean_np = np.mean(x)
print(mean_np)

8.7


In [105]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [106]:
y.mean() #array

8.7

In [107]:
z.mean() #Series

8.7

In [108]:
y_with_nan.mean()

nan

In [109]:
np.mean(y_with_nan)

nan

In [110]:
np.nan*3

nan

In [111]:
np.nanmean(y_with_nan) #get mean without considering NaN values

8.7

In [112]:
z_with_nan.mean() #Series langsung merata2kan tanpa mempertimbangkan NaN values

8.7

In [113]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

### Weighted Mean

In [114]:
x = [8,1,2.5,4,28] #Metrics
w = [0.1,0.2,0.3,0.25,0.15] #Weightages

#convert jadi array
y,z,w = np.array(x),pd.Series(x),np.array(w)

wmean = np.average(y , weights=w)
print(wmean)

6.95


In [115]:
#manual calculation
wmean_manual = sum(w[i]*x[i] for i in range(len(x)))/sum(w)
print(wmean)

6.95


In [116]:
sum(w)

1.0

### Harmonic Mean

In [117]:
speed = [60,20]
hmean_speed = len(speed)/sum(1/item for item in speed)
hmean_speed

30.0

In [118]:
# hmean dengan library 1
hmean_speed_stats = statistics.harmonic_mean(speed)
hmean_speed_stats

30.0

In [119]:
# hmean dengan library 1
hmean_speed_stats2 = scipy.stats.hmean(speed)
hmean_speed_stats2

30.0

In [120]:
x

[8, 1, 2.5, 4, 28]

In [121]:

hmean = len(x) / sum(1/item for item in x)
hmean

2.7613412228796843

In [122]:
arit_mean = np.mean(x)
arit_mean

8.7

In [123]:
x

[8, 1, 2.5, 4, 28]

In [124]:
for item in x:
    print(1/item)

0.125
1.0
0.4
0.25
0.03571428571428571


In [125]:
list(1/item for item in x)

[0.125, 1.0, 0.4, 0.25, 0.03571428571428571]

In [126]:
# hmean dgn library
hmean_stats = statistics.harmonic_mean(x)
hmean_stats

2.7613412228796843

### Geometric Mean

Perusahaan berdiri pada tahun 2017

tahun 2017 omsetnya 1000

di tahun 2018 naik 30 %

di tahun 2019 naik 50 %

di tahun 2020 naik 40 %

In [127]:
x = 1000
x*=1.3 #1300
x*=1.5 #1950
x*=1.4 #2730
x

2730.0

In [128]:
# Arithmetic Mean
(30+50+40)/3

40.0

In [129]:
x = 1000
x*=1.4
x*=1.4
x*=1.4
x

2743.9999999999995

In [130]:
#Geometric Mean
gmean = ((30*50*40)**(1/3))
gmean

39.148676411688626

In [131]:
x = 1000
x*=1.3915
x*=1.3915
x*=1.3915
x

2694.322835875

In [132]:
scipy.stats.gmean([30,50,40]) #geometric mean menggunakan library scipy

39.14867641168864

## Median

In [133]:
#Ganjil
a = [1,2,4,8,9]
n = len(a)
median = a[2]
median

4

In [134]:
#Genap
a = [1,2,4,8]
n = len(a)
(n+1)/2
median = (2+4)/2
median

3.0

In [135]:
# Menggunakan numpy
x = [8, 1, 2.5, 4, 28]
c = [2,3,4,5]
np.median(c)

3.5

In [136]:
# Pembuktian manual
def median_function(x):
    n = len(x)
    if n%2 == 1: #Ganjil
        median_ = sorted(x)[round(0.5*(n-1))] #ambil median
    else: #Genap
        x_ord, index = sorted(x) , round(0.5*n)
        median_=0.5 * (x_ord[index-1]+x_ord[index])
    return median_

In [137]:
median_function(x)

4

In [138]:
median_function(c)

3.5

In [139]:
sorted(x)

[1, 2.5, 4, 8, 28]

In [140]:
n = len([1,2,3,4,5,6,7])
round(0.5*(n-1))

3

In [141]:
n

7

## Mode/Modus

In [142]:
u = [2,3,2,8,12]

mode_ = max((u.count(i),i)for i in set(u))[1]

In [143]:
statistics.mode(u)

2

In [144]:
scipy.stats.mode(u)[0][0]

2

In [145]:
mode_lib = scipy.stats.mode(u)

In [146]:
print(mode_lib)
print(mode_lib.mode)
print(mode_lib.count)

ModeResult(mode=array([2]), count=array([2]))
[2]
[2]


In [147]:
u

[2, 3, 2, 8, 12]

In [148]:
u_series = pd.Series(u)
u_series.mode()

0    2
dtype: int64

In [149]:
u_array = np.array(u)
statistics.mode(u_array)

2

In [150]:
v = pd.Series([1,2,3,3,3,np.nan,np.nan,np.nan,np.nan])
v.mode()

0    3.0
dtype: float64

In [151]:
statistics.mode(v)

3.0

In [152]:
h = [1,2,3,3,3,np.nan,np.nan,np.nan,np.nan]
statistics.mode(h)

nan

Series akan mengabaikan NaN dan List akan mempertimbangkan NaN

# Measures of Variability

## Variance

In [153]:
x

[8, 1, 2.5, 4, 28]

In [154]:
n  = len(x)
mean_var = np.mean(x)
var_ = sum((item-mean_var)**2 for item in x ) / (n-1)
var_

123.19999999999999

In [155]:
# Variance w/ statistics library
var_stat = statistics.variance(x)
var_stat

123.2

In [156]:
# variance w/ numpy
var_np = np.var(x,ddof=1)
var_np

123.19999999999999

In [157]:
# Variance using Series function
z = pd.Series(x)
z.var()

123.19999999999999

## Standard Deviasi

In [158]:
x = [1,2,3,6,7,8,30,40,50]
std_dev = statistics.stdev(x)
print("Standar Deviasi dari x adalah:", std_dev)

variance = statistics.variance(x)
print("Variansi dari x adalah:", variance)

Standar Deviasi dari x adalah: 18.58090417606205
Variansi dari x adalah: 345.25000000000006


In [159]:
#Kuis 1 tim 4
x = [1,2,3,6,7,8,30,40,50]
n = len(x)
mean = sum(x)/n
var_ = sum((item - mean)**2 for item in x)/(n-1)
Sd_ = var_**(1/2) #

print(var_)
print(Sd_)

345.25000000000006
18.58090417606205


tim 4 poin

In [160]:
x = [8, 1, 2.5, 4, 28]

In [161]:
var_np

123.19999999999999

In [162]:
stdev = var_np**(1/2)

In [163]:
stdev

11.099549540409285

In [164]:
stdev = np.sqrt(var_np) 
stdev

11.099549540409285

In [165]:
# stdev with statistics library
stdev = statistics.stdev(x)
stdev

11.099549540409287

In [166]:
stdev = np.std(x,ddof=1)
stdev

11.099549540409285

## SKewness

In [167]:
x

[8, 1, 2.5, 4, 28]

In [168]:
n = len(x)
mean = np.mean(x)
stdev = statistics.stdev(x)
skew_ = (sum((item - mean)**3 for item in x))*n / ((n-1)*(n-2)*(stdev**3))
skew_

1.947043227390592

In [169]:
scipy.stats.skew(x,bias=False)

1.9470432273905927

In [170]:
z = pd.Series(x)
z.skew()

1.9470432273905924

In [171]:
scipy.stats.skew(x_with_nan)

nan

In [172]:
z_with_nan = pd.Series(x_with_nan)
z_with_nan.skew()

1.9470432273905924

In [173]:
scipy.stats.skew(z_with_nan)

nan

## Percentiles

In [174]:
x = [-5,-1.1,0.1,2,8,12.8,21,25.8,41]
np.percentile(x,5) #Percentile 5

-3.44

In [175]:
np.percentile(x,0)

-5.0

In [176]:
np.percentile(x,100)

41.0

In [177]:
np.percentile(x,90)

28.840000000000003

In [178]:
statistics.quantiles(x,n=2)

[8.0]

In [179]:
statistics.quantiles(x,n=4)

[-0.5, 8.0, 23.4]

In [180]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

In [181]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [182]:
np.quantile(x,0)

-5.0

In [183]:
np.quantile(x,1)

41.0

In [184]:
np.quantile(x,0.5)

8.0

In [185]:
x 

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [186]:
x_with_nan = [-5, -1.1,np.nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]
x_with_nan

[-5, -1.1, nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [187]:
np.quantile(x_with_nan,0)

nan

In [188]:
np.nanquantile(x_with_nan,0.5)

8.0

In [189]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [190]:
np.quantile(x,[0.25,0.5,0.75])

array([ 0.1,  8. , 21. ])

In [191]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

In [192]:
np.percentile(x,[25,50,75])

array([ 0.1,  8. , 21. ])

## Ranges

In [193]:
x # Ranges  = 41 - (-5) = 46

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [194]:
# np.ptp untuk menghitung range
np.ptp(x)

46.0

In [195]:
np.amax(x)

41.0

In [196]:
np.amin(x)

-5.0

In [197]:
np.amax(x) - np.amin(x)

46.0

## Interquartile Range 

Dapat digunakan untuk mencari data outlier

In [198]:
x

[-5, -1.1, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [199]:
quartiles = np.quantile(x,[0.25,0.75])
IQR = quartiles[1] - quartiles[0]
IQR

20.9

# Measure of Correlation

In [207]:
x = list(range(-10,11))
y = [0 , 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_ar, y_ar = np.array(x),np.array(y)
x_s,y_s = pd.Series(x),pd.Series(y)

In [208]:
len(x)==len(y)

True

## Covariance

In [209]:
n = len(x)
mean_x = np.mean(x)
mean_y = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y) for item in range(n)))/(n-1)
cov_xy

19.95

In [210]:
cov_matrix = np.cov(x,y)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [211]:
np.var(x,ddof=1)

38.5

In [212]:
np.var(y,ddof=1)

13.914285714285711

In [213]:
cov_xy = cov_matrix[0,1]
cov_xy

19.95

In [214]:
cov_xy = cov_matrix[1,0]
cov_xy

19.95

## Correlation Coefficient

r = 1 / r= -1 atau mendekati merupakan tanda kedua variabel mengalami multicollinearity

In [215]:
var_x = np.var(x,ddof=1)
var_y = np.var(y,ddof=1)
cov_xy
std_x = var_x**(1/2)
std_y = var_y**(1/2)
r = cov_xy / (std_x*std_y)
r

0.861950005631606

Korelasi positif sangat kuat karena sangat mendekati 1

In [216]:
r , p = scipy.stats.pearsonr(x,y)
r

0.861950005631606

In [219]:
corr_matrix = np.corrcoef(x,y)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [217]:
p

5.122760847201171e-07

In [220]:
scipy.stats.linregress(x,y)

LinregressResult(slope=0.5181818181818181, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [221]:
scipy.stats.linregress(x,y).rvalue

0.861950005631606

In [222]:
a = np.array([[1,1,1],
             [2,3,1],
             [4,9,2],
             [8,27,4],
             [16,1,1]])

In [224]:
np.mean(a)

5.4

In [225]:
np.mean(a, axis = 0)

array([6.2, 8.2, 1.8])

In [226]:
np.mean(a, axis = 1)

array([ 1.,  2.,  5., 13.,  6.])

In [230]:
np.var(a,ddof=1,axis=0)

array([ 37.2, 121.2,   1.7])

In [231]:
row_names = ['first','second','third','fourth','fifth']
col_names=['A','B','C']
df = pd.DataFrame(a,index=row_names,columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [232]:
np.mean(df.A)

6.2

In [233]:
df['A'].mean()

6.2

In [235]:
np.var(df,ddof=1)

A     37.2
B    121.2
C      1.7
dtype: float64

In [240]:
np.var(df,ddof=0)

A    29.76
B    96.96
C     1.36
dtype: float64

In [ ]:
df.mean